//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseEntities
{
    using System;
    using System.Collections.Generic;
    [Serializable]
    public partial class Creditor : IRateable, IEquatable<Creditor>
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Creditor()
        {
            this.RateSet = new HashSet<Rate>();
            Name = "empty";
        }
        public Creditor(string name, int unp, decimal sumToLoan) : base()
        {
            Name = name;
            UNP = unp;
            SumToLoan = sumToLoan;
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public double TotalRate { get; set; }
        public int UNP { get; set; }
        public decimal SumToLoan { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rate> RateSet { get; set; }

        public bool Equals(Creditor other)
        {
            return Name.Equals(other.Name) && TotalRate.Equals(other.TotalRate) && UNP.Equals(other.UNP)
                && SumToLoan.Equals(other.SumToLoan);
        }
    }
}
